kind: Template
apiVersion: v1
objects:
  - apiVersion: v1
    data:
      MINIO_ACCESS_KEY: UzBvYVdsc0Nxd09N
      MINIO_SECRET_KEY: eFhjMElic2RxYlRhVjRYdA==
    kind: Secret
    type: Opaque
    metadata:
      labels:
        app: eagle-api
      name: minio-eagle-dev
