apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
  - apiVersion: v1
    data:
      clientId: ${CLIENT_SSO_CLIENTID}
      clientSecret: ${CLIENT_SSO_SECRET}
      clientPublic: ${CLIENT_PUBLIC}
      host: ${KC_HOST}
      realmId: ${KC_REALM}
    kind: Secret
    metadata:
      name: keycloak-service-client
    type: Opaque
parameters:
  - description: OAuth Keycloak SSO client ID
    displayName: CLIENT_SSO_CLIENTID
    name: CLIENT_SSO_CLIENTID
    required: true
    value: ""
  - description: Keycloak SSO public client secret
    displayName: CLIENT_SSO_SECRET
    name: CLIENT_SSO_SECRET
    required: true
    value: ""
  - description: Keycloak SSO public client 
    displayName: CLIENT_PUBLIC
    name: CLIENT_PUBLIC
    required: true
    value: ""
  - description: Keycloak SSO realm
    displayName: KC_REALM
    name: KC_REALM
    required: true
    value: ""
  - description: Keycloak SSO host path
    displayName: KC_HOST
    name: KC_HOST
    required: true
    value: ""
