apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
objects:
  - apiVersion: v1
    data:
      CLIENT_SSO_CLIENTID: ${CLIENT_SSO_CLIENTID}
      CLIENT_SSO_SECRET: ${CLIENT_SSO_SECRET}
      CLIENT_PUBLIC: ${CLIENT_PUBLIC}
      KC_HOST: ${KC_HOST}
      KC_REALM: ${KC_REALM}
    kind: Secret
    metadata:
      name: ${NAME}
    type: Opaque
parameters:
  - description: secret name
    displayName: NAME
    name: NAME
    required: true
    value: "keycloak-service-client"
  - description: OAuth Keycloak SSO client ID
    displayName: CLIENT_SSO_CLIENTID
    name: CLIENT_SSO_CLIENTID
    required: true
    value: ""
  - description: Keycloak SSO public client secret
    displayName: CLIENT_SSO_SECRET
    name: CLIENT_SSO_SECRET
    required: true
    value: ""
  - description: Keycloak SSO public client 
    displayName: CLIENT_PUBLIC
    name: CLIENT_PUBLIC
    required: true
    value: ""
  - description: Keycloak SSO realm
    displayName: KC_REALM
    name: KC_REALM
    required: true
    value: ""
  - description: Keycloak SSO host path
    displayName: KC_HOST
    name: KC_HOST
    required: true
    value: ""
