apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eagle-admin-dev
  namespace: 6cdc9e-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: 6cdc9e
  source:
    repoURL: 'https://github.com/bcgov/eagle-admin.git'
    targetRevision: develop
    path: helm/eagle-admin
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
        - 'https://raw.githubusercontent.com/bcgov/eagle-helper-pods/master/argocd/environments/dev/values-eagle-admin.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 6cdc9e-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
