apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eao-nginx-dev
  namespace: 6cdc9e-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: epic-project
  source:
    repoURL: 'https://github.com/bcgov/eao-nginx.git'
    targetRevision: master
    path: helm/eao-nginx
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
        - 'https://raw.githubusercontent.com/bcgov/eagle-helper-pods/master/argocd/environments/dev/values-eao-nginx.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 6cdc9e-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
